version: '3'

services:

  mariadb:
    build: ${MARIADB_DIR} 
    image: mariadb:10.6.4
    container_name: mariadb_c
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - inception_network
    restart : on-failure

  wordpress:
    depends_on:
      - mariadb
    build: ${WORDPRESS_DIR} 
    image: wordpress:5.8.1-php7.4-fpm
    container_name: wordpress_c
    volumes:
      - wordpress_data:/var/www/etakouer.42.fr
      - dynamic-site_data:/var/www/dynamic-site.42.fr
      - ${WORDPRESS_DIR}/conf/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - ${WORDPRESS_DIR}/conf/php.ini:/etc/php/7.4/fpm/php.ini

    environment:
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
    networks:
      - inception_network
    restart : on-failure

  nginx:
    depends_on:
      - wordpress
    build: ${NGINX_DIR} 
    image: nginx:1.21.0
    container_name: nginx_c
    volumes:
      - ${NGINX_DIR}/conf/nginx.conf:/etc/nginx/nginx.conf
      - site_conf:/etc/nginx/conf.d
      - nginx_log:/var/log/nginx
      - wordpress_data:/var/www/etakouer.42.fr
      - static-site_data:/var/www/static-site.42.fr
      - dynamic-site_data:/var/www/dynamic-site.42.fr
      - site_ssl:/etc/ssl
    ports:
      - 443:443
    networks:
      - inception_network
    restart : on-failure

volumes:

  mariadb_data:
    name : "mariadb_data"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/mysql"

  wordpress_data:
    name : "wordpress_data"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/www/etakouer.42.fr"

  static-site_data:
    name : "static-site_data"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/www/static-site.42.fr"

  dynamic-site_data:
    name : "dynamic-site_data"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/www/dynamic-site.42.fr"

  
  site_conf:
    name : "site_conf"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${NGINX_DIR}/conf/site"
  
  site_ssl:
    name : "site_ssl"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${NGINX_DIR}/tools/ssl"

  nginx_log:
    name : "nginx_log"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/log/nginx"

networks:

  inception_network:
    name: "inception_network"
