version: '3'

services:

  mariadb:
    build:
      context: ${MARIADB_DIR} 
      args:
        MARIADB_V : ${MARIADB_V}
    image: mariadb:${MARIADB_V}
    container_name: mariadb_c
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    networks:
      - inception_network
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 3s

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ${WP_DIR} 
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
        PHP_V : ${PHP_V} 
        WP_V : ${WP_V} 
        WP_SRC : ${WP_SRC} 
    image: wordpress:${WP_V}-php${PHP_V}-fpm
    container_name: wordpress_c
    volumes:
      - wordpress_data:/var/www/${DOMAIN_NAME}
      - dynamic-site_data:/var/www/dynamic-site.42.fr
      - ${WP_DIR}/conf/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - ${WP_DIR}/conf/php.ini:/etc/php/7.4/fpm/php.ini
    environment:
      - DOMAIN_NAME
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
      - WP_TITLE
      - WP_ADMIN_LOG
      - WP_ADMIN_PASS
      - WP_ADMIN_EMAIL
      - WP_EDITOR_LOG
      - WP_EDITOR_PASS
      - WP_EDITOR_EMAIL
      - PHP_V
      - WP_SRC
    networks:
      - inception_network
    restart : on-failure

  nginx:
    depends_on:
      - wordpress
    build: 
      context: ${NGINX_DIR} 
      args:
        NGINX_V: ${NGINX_V}
    image: nginx:${NGINX_V}
    container_name: nginx_c
    volumes:
      - ${NGINX_DIR}/conf/nginx.conf:/etc/nginx/nginx.conf
      - site_conf:/etc/nginx/conf.d
      - nginx_log:/var/log/nginx
      - wordpress_data:/var/www/etakouer.42.fr
      - static-site_data:/var/www/static-site.42.fr
      - dynamic-site_data:/var/www/dynamic-site.42.fr
      - site_ssl:/etc/ssl
    ports:
      - 443:443
    networks:
      - inception_network
    restart : on-failure

  # bonus 
  
  adminer:
    depends_on:
      - mariadb
    image: adminer:4.8.1
    container_name: adminer_c
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - inception_network

  redis:
    depends_on:
      - wordpress
    image: redis:${REDIS_V}
    build:
      context: ${REDIS_DIR}
      args:
        REDIS_V: ${REDIS_V}
    container_name: redis_c
    restart: on-failure
    volumes:
      - redis_data:/data
      - ${REDIS_DIR}/conf/redis.conf:/etc/redis/redis.conf
    networks:
      - inception_network

volumes:

  mariadb_data:
    name : "mariadb_data"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/mysql"

  wordpress_data:
    name : "wordpress_data"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/www/etakouer.42.fr"

  static-site_data:
    name : "static-site_data"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/www/static-site.42.fr"

  dynamic-site_data:
    name : "dynamic-site_data"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/www/dynamic-site.42.fr"

  redis_data:
    name : "redis_data"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/redis"
  
  site_conf:
    name : "site_conf"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${NGINX_DIR}/conf/site"
  
  site_ssl:
    name : "site_ssl"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${NGINX_DIR}/tools/ssl"

  nginx_log:
    name : "nginx_log"
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DATA_PATH}/log/nginx"

networks:

  inception_network:
    name: "inception_network"
